version: "0.1"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - trainBookingService-db:/var/lib/postgresql/data
  soap-service:
    container_name: soap-service
    build:
      context: SOAPService/.
    ports:
      - "8080:8080"
  rest-service:
    container_name: rest-service
    build:
      context: RESTService/.
    ports:
      - "3000:3000"
    environment:
      EXTERNAL_PORT: 3000
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: trainbookingservice
      PG_HOST: postgres
    depends_on:
      - postgres
      - soap-service


volumes:
  trainBookingService-db: