version: "0.1"
services:
  trainbooking-db:
    container_name: trainbooking-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trainbooking
    ports:
      - "3306:3306"
    volumes:
      - trainbooking-db-volume:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
  sncf-db:
    container_name: sncf-db
    image: postgres
    environment:
      POSTGRES_USER: sncf
      POSTGRES_PASSWORD: sncf
    ports:
      - '5432:5432'
    volumes:
      - sncf-db-volume:/var/lib/postgresql/data
  soap-service:
    container_name: soap-service
    build:
      context: SOAPService/.
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: jdbc:mysql://trainbooking-db:3306/trainbooking
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      REST_ENDPOINT: http://rest-service:3000/
  rest-service:
    container_name: rest-service
    build:
      context: RESTService/.
    ports:
      - "3000:3000"
    environment:
      EXTERNAL_PORT: 3000
      PG_USER: sncf
      PG_PASSWORD: sncf
      PG_DATABASE: sncf
      PG_HOST: sncf-db
    depends_on:
      - sncf-db
      - soap-service

volumes:
  sncf-db-volume:
  trainbooking-db-volume: