version: "0.1"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - trainBookingService-db:/var/lib/postgresql/data

volumes:
  trainBookingService-db: